global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "bootstrap"
    static_configs:
      - targets: ["bootstrap:9898"]

  - job_name: "chat-nodes"
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        regex: rustchatroom
        action: keep
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: chat-node
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __meta_kubernetes_pod_port_name
